### ISSUE TITLE
[Documentation] using `flag name` in the code comments

### ISSUE THREAD

**Issue by chenrui333** [launchdarkly/ld-find-code-refs#150]
It looks like currently the following code reference can be supported by code push. 

### working

```scala
object class {
  // `flag-name`
}
```

### not working

```scala
object class {
  // flag-name
}
```

I wonder if it can be documented somewhere for reference. Thanks!

**Comment by InTheCloudDan** [comment]
@chenrui333 can you let us know the expected use case for finding flag keys in the comments? The reason we have the built in delimiters if so that it does not find every possible instance of the word. And with code references you do have the option for adding lines of context around where that flag was found.

**Comment by jazanne** [comment]
@chenrui333 We have documented the use of delimiters when finding flags here: 

https://github.com/launchdarkly/ld-find-code-refs/blob/main/docs/CONFIGURATION.md#delimiters

Please let us know if you have any feedback.

**Comment by chenrui333** [comment]
I think I am all good, closing this issue.
