### ISSUE TITLE
Include file types

### ISSUE THREAD

**Issue by gtevans** [launchdarkly/ld-find-code-refs#78]
Do you have any plans to have an include file types parameter rather than an ignore file types? My scenario would be to search in *.ts and *.cs files, which would be a lot easier to include these rather than exclude all others.

Thanks

**Comment by atrakh** [comment]
Hi @gtevans,

For anything more advanced a simple directory or filetype exclude regex, we'd recommend specifying  a [`.ldignore`](https://github.com/launchdarkly/ld-find-code-refs#ignoring-files-and-directories) file in the root dir of your repo to specify paths for `ld-find-code-refs`. 

The negation operator (as specified by https://git-scm.com/docs/gitignore#_pattern_format) can be used to specify includes.

Example `.ldignore` to only match `.ts` and `.cs` files:
```
!*.ts
!*.cs
```

**Comment by gtevans** [comment]
@atrakh I can't get adding the file types to a .ldignore file to work.

To simplify the issue I added a .ldignore file to the root of my repository and added only a '*' in the file, with the expectation that all files should be ignored and no flags would be picked up by the tool. This wasn't the case and all flags were picked up. 

Any ideas?

**Comment by atrakh** [comment]
Thanks for following up- what you've described is not expected behavior.

To troubleshoot, can you please confirm that you're running the latest version of `ld-find-code-refs`? The current latest version if 1.0.0. You can find out which version you're running by executing the command line utility with the `-version` parameter. If that command line option does not exist, it's likely you're running an older version.

If you are encountering this issue on 1.0.0, some additional information about how you're executing `ld-find-code-refs` would be useful to troubleshoot, including:
- How you've installed `ld-find-code-refs` (GitHub actions, homebrew, downloaded a release, etc.)
- Which operating system `ld-find-code-refs` is executing on
- If you're executing CLI manually, it would be useful to see the command being executed

**Comment by gtevans** [comment]
@atrakh I am on version 1.0.0, I downloaded the release via github, using ld-find-code-refs_1.0.0_windows_amd64, running the cli manually.

Command - ld-find-code-refs.exe -accessToken=api-*** -projKey="***" -repoName="***" -dir="***" -debug=true -repoUrl="http://***" -contextLines=5 -repoUrl="http://***" -commitUrlTemplate="http://***/${sha}"

Can you update the exe to output a debug statement if the .ldignore file is found / used?

If you want to see the output of the application can you share your email address and I can send over a screencast.

**Comment by atrakh** [comment]
Thanks for the update @gtevans.

While I haven't yet been able to reproduce this issue (I'm testing on Windows 10 and `ag --version` 2.1.0), we did just publish a [1.0.1 release](https://github.com/launchdarkly/ld-find-code-refs/releases). 1.0.1 contains a potentially related fix for path resolution of the `.ldignore` file, and now debug logs when the `.ldignore` file is found.

Hopefully, this change resolves your issue. If not, please do send over the program output to arnold@launchdarkly.com.

**Comment by atrakh** [comment]
Looping a summary of our email discussion back in here for posterity:

The negation operator is not fully support by the underlying search tool used by `ld-find-code-refs`. The example for using the negation operator to only search for certain file types **does not work** for files in subdirectories.

At this time, we have plans to add support for a new option that allows a list of file types to be specified. By default, all files will be searched. If the option is provided, searches will be limited to the specified file types.

**Comment by atrakh** [comment]
Using the negation operator to include previously excluded subdirectories is now supported as of [2.0.0](https://github.com/launchdarkly/ld-find-code-refs/releases/tag/2.0.0).

The [example above](https://github.com/launchdarkly/ld-find-code-refs/issues/78#issuecomment-471060517) should now work.
