### ISSUE TITLE
CI against a detached commit fails branch name parsing

### ISSUE THREAD

**Issue by sethbattin** [launchdarkly/ld-find-code-refs#84]
While running `ls-find-code-refs` within AWS codebuild, the utility fails because it cannot acquire the current branch name.  Presumably this happens because the utility acquires that info from git directly, and codebuild executes on specific commits rather than a checked-out branch.

The failure yields this error, from either the docker image or the prebuilt binary:
> ERROR: 2019/05/03 22:28:55 coderefs.go:66: error parsing git branch name: git repo at /codebuild/output/src111794365/src/{REPO}/src must be checked out to a valid branch

There is a simple workaround for this problem, which is to explicitly execute `git checkout ${BRANCH}` prior to running the utility in the build spec file.

This is a small risk because multiple simultaneous CI runs can happen against one branch.  My org runs codebuild against every commit, and uses the results to update github's status API to control PR merge access.  It is plausible that changing to the head commit of a given branch might produce an error due to a race condition.  Obviously this is not a huge concern for this specific problem, because this utility is not build-critical.  Also the actual flag names _probably_ don't change with each individual commit, so tracking them exactly is unnecessary for our purposes.  Still, it would be nice to not have to use the workaround.

---

Possible solution: add a CLI argument to declare the branch name directly, rather than infer it from git?

I'm reporting this issue as an FYI more than an urgent request, so I'm not too invested in resolving it in any particular way.  If you need any more info, please comment so.  

Thanks.

**Comment by atrakh** [comment]
Hi @sethbattin,

Thanks for reaching out. I'm not incredibly familiar with AWS codebuild, so please let me know if any of the following is off-base.

Can you expand a bit more on how this race condition can occur? To my understanding, the race condition you're referring to is a result of `ld-find-code-refs` potentially running out of order across a number of concurrent builds. The concern here would be that the last code reference data sent to LaunchDarkly could be for a commit that is not the most recent.

If the above is correct, our recommendation would be to use the `updateSequenceId` command-line argument to version your commits. `updateSequenceId` should be a monotonically increasing number. 

Depending on what's available in your build environment, this could be something like the build number, or the time a build was triggered (not the time it actually started, for systems that do concurrent or potentially out of order executions).

**Re: add a CLI argument to declare the branch name directly, rather than infer it from git?**
If my understanding above is correct, I'm not sure this would completely resolve the issue. Although, this could be a solution for systems that are not able to checkout to a branch under any circumstances.

Hope that helps,
Arnold

**Comment by atrakh** [comment]
@sethbattin 

Haven't heard back for a while, so I'm going to close this issue for now. If the above comment does not satisfy your concerns, please do reply and we can pick things up where we left off 😄
